Repository NetScape-Web/hacktoberfest2021, pull requests merged in 2021-10, with the labels that each got.

#1 Environment Setup For Hacktoberfest 2021 Contributers
  Algorithms/Array/README.md
  Algorithms/LinkedList/README.md
  Algorithms/Queue/README.md
  Algorithms/README.md
  Algorithms/Stack/README.md
  Algorithms/Tree/README.md
  C++/README.md
  C/README.md
  Java/README.md
  JavaScript/README.md
  Python/README.md
  Web_Development/CSS/README.md
  Web_Development/HTML/README.md
  Web_Development/README.md
Labels: good first pull request

#4 bank system
  C++/classbank.cpp
Labels: good first pull request

#5 Create shellSort.java
  Java/shellSort.java
Labels: good first pull request

#7 Add a simple BST implementation
  Algorithms/Tree/simple_bst.cc
  Algorithms/Tree/simple_bst.hpp
Labels: good first pull request

#9 Add Rust folder and guessing game
  Rust/README.md
  Rust/guessing_game/.gitignore
  Rust/guessing_game/Cargo.lock
  Rust/guessing_game/Cargo.toml
  Rust/guessing_game/src/main.rs
Labels: new feature

#8 Create ticTacToe.py
  Python/ticTacToe.py
Labels: enhancement

#11 Add CONTRIBUTING.md PROFILE.md files
  CONTRIBUTING.md
  PROFILE.md
Labels: enhancement

#10 Create fizzBuzz.cpp
  C++/fizzBuzz.cpp
  PROFILE.md
Labels: documentation

#16 Healthy Programmer
  Python/Healthy Programmer.py
Labels: good first pull request

#44 create BST in java
  Java/binary_search_tree.java
Labels: good first pull request
